name: Build Tauri Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # Mencegah terminal macet karena menunggu input keyboard (Enter)
      CI: true 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android

      - name: Install Android SDK & NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125"
          echo "NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Install Frontend Dependencies
        run: npm install

      - name: Fix Tauri Identifier
        run: sed -i 's/"com.tauri.dev"/"com.masjid.tv"/g' src-tauri/tauri.conf.json || true

      - name: Init Tauri Android
        run: npx tauri android init || true

      - name: Bypass Frontend Build
        run: npm pkg set scripts.build="echo 'No build required'"

      - name: Build APK Android
        run: npx tauri android build --apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Jadwal-Sholat
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk